# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: nix flake update

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: main
      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Check out Doom core
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: doomemacs/core
          path: doomemacs
      - name: Update and push flake.lock
        run: |
          core_rev=$(git --git-dir=doomemacs/.git rev-parse HEAD)
          modules_rev=$(
            git --git-dir=doomemacs/.git submodule status --cached sources/doom+ |
            sed -Ee 's/^-([0-9a-f]+) .*/\1/')
          echo "core rev: $core_rev, modules rev: $modules_rev"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git checkout -b flake-update
          nix flake update --commit-lock-file \
            --override-input doomemacs "github:doomemacs/core/$core_rev" \
            --override-input doomemacs-modules "github:doomemacs/modules/$modules_rev"
          git push --force origin flake-update
